[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[fmt]
number_underscore = "thousands"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
local = "http://localhost:8545"
